name: Deploy to Dokku

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
        with:
          fetch-depth: 0

      - uses: dokku/github-action@b7a4a52588b8b8879d21d4ba9c0fc7cbdbc94e15  # v1.4.0
        with:
          git_remote_url: ${{ secrets.DOKKU_REMOTE_URL }}
          ssh_private_key: ${{ secrets.DOKKU_SSH_KEY }}
